-- Auto-generated by prep-gas on: 12-Sep-2017 12:24:47

model = 'IdealGas'
IdealGas = {
   speciesName = 'CO2',
   mMass = 0.04401000,
   gamma = 1.30000000,
   entropyRefValues = {
      s1 = 0.00000000e+00,
      T1 = 298.15000000,
      p1 = 1.01325000e+05,
   },
   viscosity = {
      model = 'Sutherland',
      mu_ref = 1.48000000e-05,
      T_ref = 293.15000000,
      S = 240.00000000,
   },
   thermCondModel = {
      model = 'Sutherland',
      k_ref = 2.41000000e-02,
      T_ref = 273.00000000,
      S = 194.00000000,
   }
}
