-- Auto-generated by prep-gas on: 17-Oct-2017 23:27:30

model = 'IdealGas'
IdealGas = {
   speciesName = 'H2O',
   mMass = 0.01801528,
   gamma = 1.32900000,
   entropyRefValues = {
      s1 = 0.00000000e+00,
      T1 = 298.15000000,
      p1 = 1.01325000e+05,
   },
   viscosity = {
      model = 'CEA',
      nsegments = 3,
      segment0 = {
         T_lower = 373.2,
         T_upper = 1073.2,
         A =  5.0019557e-01,
         B = -6.9712796e+02,
         C =  8.8163892e+04,
         D =  3.0836508e+00,
      },
      segment1 = {
         T_lower = 1073.2,
         T_upper = 5000.0,
         A =  5.8988538e-01,
         B = -5.3769814e+02,
         C =  5.4263513e+04,
         D =  2.3386375e+00,
      },
      segment2 = {
         T_lower = 5000.0,
         T_upper = 15000.0,
         A =  6.4330087e-01,
         B = -9.5668913e+01,
         C = -3.7742283e+05,
         D =  1.8125190e+00,
      },
   },
   thermCondModel = {
      model = 'CEA',
      nsegments = 3,
      segment0 = {
         T_lower = 373.2,
         T_upper = 1073.2,
         A =  1.0966389e+00,
         B = -5.5513429e+02,
         C =  1.0623408e+05,
         D = -2.4664550e-01,
      },
      segment1 = {
         T_lower = 1073.2,
         T_upper = 5000.0,
         A =  3.9367933e-01,
         B = -2.2524226e+03,
         C =  6.1217458e+05,
         D =  5.8011317e+00,
      },
      segment2 = {
         T_lower = 5000.0,
         T_upper = 15000.0,
         A = -4.1858737e-01,
         B = -1.4096649e+04,
         C =  1.9179190e+07,
         D =  1.4345613e+01,
      },
   }
}
